/**
 * @file gbt27930.h
 *
 * @brief This header file was generated by cantools version 41.2.1 Fri Mar 13 18:52:59 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef GBT27930_H
#define GBT27930_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define GBT27930_BHM_FRAME_ID (0x182756f4u)
#define GBT27930_BRM_FRAME_ID (0x1c0256f4u)
#define GBT27930_BCP_FRAME_ID (0x1c0656f4u)
#define GBT27930_BRO_FRAME_ID (0x100956f4u)
#define GBT27930_BCL_FRAME_ID (0x181056f4u)
#define GBT27930_BCS_FRAME_ID (0x1c1156f4u)
#define GBT27930_BSM_FRAME_ID (0x181356f4u)
#define GBT27930_BMV_FRAME_ID (0x1c1556f4u)
#define GBT27930_BMT_FRAME_ID (0x1c1656f4u)
#define GBT27930_BSP_FRAME_ID (0x1c1756f4u)
#define GBT27930_BST_FRAME_ID (0x101956f4u)
#define GBT27930_BSD_FRAME_ID (0x181c56f4u)
#define GBT27930_BEM_FRAME_ID (0x81e56f4u)
#define GBT27930_CHM_FRAME_ID (0x1826f456u)
#define GBT27930_CRM_FRAME_ID (0x1801f456u)
#define GBT27930_CTS_FRAME_ID (0x1807f456u)
#define GBT27930_CML_FRAME_ID (0x1808f456u)
#define GBT27930_CRO_FRAME_ID (0x100af456u)
#define GBT27930_CCS_FRAME_ID (0x1812f456u)
#define GBT27930_CST_FRAME_ID (0x101af456u)
#define GBT27930_CSD_FRAME_ID (0x181df456u)
#define GBT27930_CEM_FRAME_ID (0x81ff456u)

/* Frame lengths in bytes. */
#define GBT27930_BHM_LENGTH (8u)
#define GBT27930_BRM_LENGTH (8u)
#define GBT27930_BCP_LENGTH (8u)
#define GBT27930_BRO_LENGTH (8u)
#define GBT27930_BCL_LENGTH (8u)
#define GBT27930_BCS_LENGTH (8u)
#define GBT27930_BSM_LENGTH (8u)
#define GBT27930_BMV_LENGTH (8u)
#define GBT27930_BMT_LENGTH (8u)
#define GBT27930_BSP_LENGTH (8u)
#define GBT27930_BST_LENGTH (8u)
#define GBT27930_BSD_LENGTH (8u)
#define GBT27930_BEM_LENGTH (8u)
#define GBT27930_CHM_LENGTH (8u)
#define GBT27930_CRM_LENGTH (8u)
#define GBT27930_CTS_LENGTH (8u)
#define GBT27930_CML_LENGTH (8u)
#define GBT27930_CRO_LENGTH (8u)
#define GBT27930_CCS_LENGTH (8u)
#define GBT27930_CST_LENGTH (8u)
#define GBT27930_CSD_LENGTH (8u)
#define GBT27930_CEM_LENGTH (8u)

/* Extended or standard frame types. */
#define GBT27930_BHM_IS_EXTENDED (1)
#define GBT27930_BRM_IS_EXTENDED (1)
#define GBT27930_BCP_IS_EXTENDED (1)
#define GBT27930_BRO_IS_EXTENDED (1)
#define GBT27930_BCL_IS_EXTENDED (1)
#define GBT27930_BCS_IS_EXTENDED (1)
#define GBT27930_BSM_IS_EXTENDED (1)
#define GBT27930_BMV_IS_EXTENDED (1)
#define GBT27930_BMT_IS_EXTENDED (1)
#define GBT27930_BSP_IS_EXTENDED (1)
#define GBT27930_BST_IS_EXTENDED (1)
#define GBT27930_BSD_IS_EXTENDED (1)
#define GBT27930_BEM_IS_EXTENDED (1)
#define GBT27930_CHM_IS_EXTENDED (1)
#define GBT27930_CRM_IS_EXTENDED (1)
#define GBT27930_CTS_IS_EXTENDED (1)
#define GBT27930_CML_IS_EXTENDED (1)
#define GBT27930_CRO_IS_EXTENDED (1)
#define GBT27930_CCS_IS_EXTENDED (1)
#define GBT27930_CST_IS_EXTENDED (1)
#define GBT27930_CSD_IS_EXTENDED (1)
#define GBT27930_CEM_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define GBT27930_BHM_NAME "BHM"
#define GBT27930_BRM_NAME "BRM"
#define GBT27930_BCP_NAME "BCP"
#define GBT27930_BRO_NAME "BRO"
#define GBT27930_BCL_NAME "BCL"
#define GBT27930_BCS_NAME "BCS"
#define GBT27930_BSM_NAME "BSM"
#define GBT27930_BMV_NAME "BMV"
#define GBT27930_BMT_NAME "BMT"
#define GBT27930_BSP_NAME "BSP"
#define GBT27930_BST_NAME "BST"
#define GBT27930_BSD_NAME "BSD"
#define GBT27930_BEM_NAME "BEM"
#define GBT27930_CHM_NAME "CHM"
#define GBT27930_CRM_NAME "CRM"
#define GBT27930_CTS_NAME "CTS"
#define GBT27930_CML_NAME "CML"
#define GBT27930_CRO_NAME "CRO"
#define GBT27930_CCS_NAME "CCS"
#define GBT27930_CST_NAME "CST"
#define GBT27930_CSD_NAME "CSD"
#define GBT27930_CEM_NAME "CEM"

/* Signal Names. */
#define GBT27930_BHM_BMS_VERSION_NAME "bms_version"
#define GBT27930_BHM_BATTERY_CAPACITY_NAME "battery_capacity"
#define GBT27930_BHM_NOMINAL_VOLTAGE_NAME "nominal_voltage"
#define GBT27930_BHM_BATTERY_TYPE_NAME "battery_type"
#define GBT27930_BHM_MANUFACTURER_ID_NAME "manufacturer_id"
#define GBT27930_BRM_SERIES_CELLS_NAME "series_cells"
#define GBT27930_BRM_PARALLEL_CELLS_NAME "parallel_cells"
#define GBT27930_BRM_PACK_CAPACITY_NAME "pack_capacity"
#define GBT27930_BCP_MAX_CHARGE_VOLTAGE_NAME "max_charge_voltage"
#define GBT27930_BCP_MAX_CHARGE_CURRENT_NAME "max_charge_current"
#define GBT27930_BCP_ENERGY_CAPACITY_NAME "energy_capacity"
#define GBT27930_BRO_BMS_READY_NAME "bms_ready"
#define GBT27930_BCL_REQUESTED_VOLTAGE_NAME "requested_voltage"
#define GBT27930_BCL_REQUESTED_CURRENT_NAME "requested_current"
#define GBT27930_BCL_CHARGE_MODE_NAME "charge_mode"
#define GBT27930_BCS_BATTERY_VOLTAGE_NAME "battery_voltage"
#define GBT27930_BCS_BATTERY_CURRENT_NAME "battery_current"
#define GBT27930_BCS_SOC_NAME "soc"
#define GBT27930_BCS_BATTERY_TEMP_NAME "battery_temp"
#define GBT27930_BSM_MAX_TEMP_NAME "max_temp"
#define GBT27930_BSM_MIN_TEMP_NAME "min_temp"
#define GBT27930_BMV_MAX_CELL_VOLTAGE_NAME "max_cell_voltage"
#define GBT27930_BMV_MIN_CELL_VOLTAGE_NAME "min_cell_voltage"
#define GBT27930_BMT_MAX_TEMP_CELL_NAME "max_temp_cell"
#define GBT27930_BMT_MIN_TEMP_CELL_NAME "min_temp_cell"
#define GBT27930_BSP_STOP_REASON_NAME "stop_reason"
#define GBT27930_BST_STOP_FLAG_NAME "stop_flag"
#define GBT27930_BST_FAULT_CODE_NAME "fault_code"
#define GBT27930_BSD_DISCHARGE_TIME_NAME "discharge_time"
#define GBT27930_BEM_ERROR_CODE_NAME "error_code"
#define GBT27930_CHM_CHARGER_MAX_VOLTAGE_NAME "charger_max_voltage"
#define GBT27930_CHM_CHARGER_MAX_CURRENT_NAME "charger_max_current"
#define GBT27930_CHM_CHARGER_TYPE_NAME "charger_type"
#define GBT27930_CRM_CHARGER_READY_NAME "charger_ready"
#define GBT27930_CRM_CHARGER_STATUS_NAME "charger_status"
#define GBT27930_CTS_ESTIMATED_CHARGE_TIME_NAME "estimated_charge_time"
#define GBT27930_CML_CHARGER_MODE_NAME "charger_mode"
#define GBT27930_CRO_CHARGER_READY_TO_CHARGE_NAME "charger_ready_to_charge"
#define GBT27930_CCS_OUTPUT_VOLTAGE_NAME "output_voltage"
#define GBT27930_CCS_OUTPUT_CURRENT_NAME "output_current"
#define GBT27930_CCS_CHARGER_TEMP_NAME "charger_temp"
#define GBT27930_CCS_CHARGER_STATUS_NAME "charger_status"
#define GBT27930_CST_STOP_REASON_NAME "stop_reason"
#define GBT27930_CST_FAULT_CODE_NAME "fault_code"
#define GBT27930_CSD_DISCHARGE_TIME_NAME "discharge_time"
#define GBT27930_CEM_ERROR_CODE_NAME "error_code"

/**
 * Signals in message BHM.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bhm_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bms_version;

    /**
     * Range: 0..10000 (0..1000 Ah)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t battery_capacity;

    /**
     * Range: 0..10000 (0..1000 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t nominal_voltage;

    /**
     * Range: 0..10 (0..10 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t battery_type;

    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t manufacturer_id;
};

/**
 * Signals in message BRM.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_brm_t {
    /**
     * Range: 0..1000 (0..1000 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t series_cells;

    /**
     * Range: 0..1000 (0..1000 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t parallel_cells;

    /**
     * Range: 0..10000 (0..1000 Ah)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t pack_capacity;
};

/**
 * Signals in message BCP.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bcp_t {
    /**
     * Range: 0..10000 (0..1000 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t max_charge_voltage;

    /**
     * Range: 0..5000 (0..500 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t max_charge_current;

    /**
     * Range: 0..10000 (0..1000 kWh)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t energy_capacity;
};

/**
 * Signals in message BRO.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bro_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bms_ready;
};

/**
 * Signals in message BCL.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bcl_t {
    /**
     * Range: 0..10000 (0..1000 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t requested_voltage;

    /**
     * Range: 0..5000 (0..500 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t requested_current;

    /**
     * Range: 0..5 (0..5 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charge_mode;
};

/**
 * Signals in message BCS.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bcs_t {
    /**
     * Range: 0..10000 (0..1000 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t battery_voltage;

    /**
     * Range: -5000..5000 (-500..500 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t battery_current;

    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t soc;

    /**
     * Range: 0..160 (-40..120 C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t battery_temp;
};

/**
 * Signals in message BSM.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bsm_t {
    /**
     * Range: 0..160 (-40..120 C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t max_temp;

    /**
     * Range: 0..160 (-40..120 C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t min_temp;
};

/**
 * Signals in message BMV.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bmv_t {
    /**
     * Range: 0..5000 (0..5 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t max_cell_voltage;

    /**
     * Range: 0..5000 (0..5 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t min_cell_voltage;
};

/**
 * Signals in message BMT.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bmt_t {
    /**
     * Range: 0..160 (-40..120 C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t max_temp_cell;

    /**
     * Range: 0..160 (-40..120 C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t min_temp_cell;
};

/**
 * Signals in message BSP.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bsp_t {
    /**
     * Range: 0..20 (0..20 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_reason;
};

/**
 * Signals in message BST.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bst_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_flag;

    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t fault_code;
};

/**
 * Signals in message BSD.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bsd_t {
    /**
     * Range: 0..65535 (0..65535 s)
     * Scale: 1
     * Offset: 0
     */
    uint16_t discharge_time;
};

/**
 * Signals in message BEM.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_bem_t {
    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t error_code;
};

/**
 * Signals in message CHM.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_chm_t {
    /**
     * Range: 0..10000 (0..1000 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t charger_max_voltage;

    /**
     * Range: 0..5000 (0..500 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t charger_max_current;

    /**
     * Range: 0..10 (0..10 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charger_type;
};

/**
 * Signals in message CRM.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_crm_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charger_ready;

    /**
     * Range: 0..10 (0..10 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charger_status;
};

/**
 * Signals in message CTS.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_cts_t {
    /**
     * Range: 0..65535 (0..65535 s)
     * Scale: 1
     * Offset: 0
     */
    uint16_t estimated_charge_time;
};

/**
 * Signals in message CML.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_cml_t {
    /**
     * Range: 0..5 (0..5 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charger_mode;
};

/**
 * Signals in message CRO.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_cro_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charger_ready_to_charge;
};

/**
 * Signals in message CCS.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_ccs_t {
    /**
     * Range: 0..10000 (0..1000 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t output_voltage;

    /**
     * Range: 0..5000 (0..500 A)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t output_current;

    /**
     * Range: 0..160 (-40..120 C)
     * Scale: 1
     * Offset: -40
     */
    uint8_t charger_temp;

    /**
     * Range: 0..10 (0..10 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charger_status;
};

/**
 * Signals in message CST.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_cst_t {
    /**
     * Range: 0..20 (0..20 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t stop_reason;

    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t fault_code;
};

/**
 * Signals in message CSD.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_csd_t {
    /**
     * Range: 0..65535 (0..65535 s)
     * Scale: 1
     * Offset: 0
     */
    uint16_t discharge_time;
};

/**
 * Signals in message CEM.
 *
 * All signal values are as on the CAN bus.
 */
struct gbt27930_cem_t {
    /**
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t error_code;
};

/**
 * Pack message BHM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bhm_pack(
    uint8_t *dst_p,
    const struct gbt27930_bhm_t *src_p,
    size_t size);

/**
 * Unpack message BHM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bhm_unpack(
    struct gbt27930_bhm_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BHM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bhm_init(struct gbt27930_bhm_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bhm_bms_version_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bhm_bms_version_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bhm_bms_version_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bhm_battery_capacity_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bhm_battery_capacity_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bhm_battery_capacity_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bhm_nominal_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bhm_nominal_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bhm_nominal_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bhm_battery_type_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bhm_battery_type_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bhm_battery_type_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bhm_manufacturer_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bhm_manufacturer_id_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bhm_manufacturer_id_is_in_range(uint16_t value);

/**
 * Pack message BRM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_brm_pack(
    uint8_t *dst_p,
    const struct gbt27930_brm_t *src_p,
    size_t size);

/**
 * Unpack message BRM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_brm_unpack(
    struct gbt27930_brm_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BRM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_brm_init(struct gbt27930_brm_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_brm_series_cells_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_brm_series_cells_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_brm_series_cells_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_brm_parallel_cells_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_brm_parallel_cells_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_brm_parallel_cells_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_brm_pack_capacity_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_brm_pack_capacity_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_brm_pack_capacity_is_in_range(uint16_t value);

/**
 * Pack message BCP.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bcp_pack(
    uint8_t *dst_p,
    const struct gbt27930_bcp_t *src_p,
    size_t size);

/**
 * Unpack message BCP.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bcp_unpack(
    struct gbt27930_bcp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BCP.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bcp_init(struct gbt27930_bcp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bcp_max_charge_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcp_max_charge_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcp_max_charge_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bcp_max_charge_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcp_max_charge_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcp_max_charge_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bcp_energy_capacity_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcp_energy_capacity_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcp_energy_capacity_is_in_range(uint16_t value);

/**
 * Pack message BRO.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bro_pack(
    uint8_t *dst_p,
    const struct gbt27930_bro_t *src_p,
    size_t size);

/**
 * Unpack message BRO.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bro_unpack(
    struct gbt27930_bro_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BRO.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bro_init(struct gbt27930_bro_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bro_bms_ready_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bro_bms_ready_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bro_bms_ready_is_in_range(uint8_t value);

/**
 * Pack message BCL.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bcl_pack(
    uint8_t *dst_p,
    const struct gbt27930_bcl_t *src_p,
    size_t size);

/**
 * Unpack message BCL.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bcl_unpack(
    struct gbt27930_bcl_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BCL.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bcl_init(struct gbt27930_bcl_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bcl_requested_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcl_requested_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcl_requested_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bcl_requested_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcl_requested_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcl_requested_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bcl_charge_mode_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcl_charge_mode_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcl_charge_mode_is_in_range(uint8_t value);

/**
 * Pack message BCS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bcs_pack(
    uint8_t *dst_p,
    const struct gbt27930_bcs_t *src_p,
    size_t size);

/**
 * Unpack message BCS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bcs_unpack(
    struct gbt27930_bcs_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BCS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bcs_init(struct gbt27930_bcs_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bcs_battery_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcs_battery_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcs_battery_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bcs_battery_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcs_battery_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcs_battery_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bcs_soc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcs_soc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcs_soc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bcs_battery_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bcs_battery_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bcs_battery_temp_is_in_range(uint8_t value);

/**
 * Pack message BSM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bsm_pack(
    uint8_t *dst_p,
    const struct gbt27930_bsm_t *src_p,
    size_t size);

/**
 * Unpack message BSM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bsm_unpack(
    struct gbt27930_bsm_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BSM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bsm_init(struct gbt27930_bsm_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bsm_max_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bsm_max_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bsm_max_temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bsm_min_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bsm_min_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bsm_min_temp_is_in_range(uint8_t value);

/**
 * Pack message BMV.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bmv_pack(
    uint8_t *dst_p,
    const struct gbt27930_bmv_t *src_p,
    size_t size);

/**
 * Unpack message BMV.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bmv_unpack(
    struct gbt27930_bmv_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMV.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bmv_init(struct gbt27930_bmv_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bmv_max_cell_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bmv_max_cell_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bmv_max_cell_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bmv_min_cell_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bmv_min_cell_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bmv_min_cell_voltage_is_in_range(uint16_t value);

/**
 * Pack message BMT.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bmt_pack(
    uint8_t *dst_p,
    const struct gbt27930_bmt_t *src_p,
    size_t size);

/**
 * Unpack message BMT.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bmt_unpack(
    struct gbt27930_bmt_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BMT.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bmt_init(struct gbt27930_bmt_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bmt_max_temp_cell_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bmt_max_temp_cell_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bmt_max_temp_cell_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bmt_min_temp_cell_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bmt_min_temp_cell_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bmt_min_temp_cell_is_in_range(uint8_t value);

/**
 * Pack message BSP.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bsp_pack(
    uint8_t *dst_p,
    const struct gbt27930_bsp_t *src_p,
    size_t size);

/**
 * Unpack message BSP.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bsp_unpack(
    struct gbt27930_bsp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BSP.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bsp_init(struct gbt27930_bsp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bsp_stop_reason_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bsp_stop_reason_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bsp_stop_reason_is_in_range(uint8_t value);

/**
 * Pack message BST.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bst_pack(
    uint8_t *dst_p,
    const struct gbt27930_bst_t *src_p,
    size_t size);

/**
 * Unpack message BST.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bst_unpack(
    struct gbt27930_bst_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BST.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bst_init(struct gbt27930_bst_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_bst_stop_flag_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bst_stop_flag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bst_stop_flag_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bst_fault_code_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bst_fault_code_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bst_fault_code_is_in_range(uint16_t value);

/**
 * Pack message BSD.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bsd_pack(
    uint8_t *dst_p,
    const struct gbt27930_bsd_t *src_p,
    size_t size);

/**
 * Unpack message BSD.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bsd_unpack(
    struct gbt27930_bsd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BSD.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bsd_init(struct gbt27930_bsd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bsd_discharge_time_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bsd_discharge_time_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bsd_discharge_time_is_in_range(uint16_t value);

/**
 * Pack message BEM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_bem_pack(
    uint8_t *dst_p,
    const struct gbt27930_bem_t *src_p,
    size_t size);

/**
 * Unpack message BEM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_bem_unpack(
    struct gbt27930_bem_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from BEM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_bem_init(struct gbt27930_bem_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_bem_error_code_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_bem_error_code_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_bem_error_code_is_in_range(uint16_t value);

/**
 * Pack message CHM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_chm_pack(
    uint8_t *dst_p,
    const struct gbt27930_chm_t *src_p,
    size_t size);

/**
 * Unpack message CHM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_chm_unpack(
    struct gbt27930_chm_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CHM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_chm_init(struct gbt27930_chm_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_chm_charger_max_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_chm_charger_max_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_chm_charger_max_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_chm_charger_max_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_chm_charger_max_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_chm_charger_max_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_chm_charger_type_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_chm_charger_type_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_chm_charger_type_is_in_range(uint8_t value);

/**
 * Pack message CRM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_crm_pack(
    uint8_t *dst_p,
    const struct gbt27930_crm_t *src_p,
    size_t size);

/**
 * Unpack message CRM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_crm_unpack(
    struct gbt27930_crm_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CRM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_crm_init(struct gbt27930_crm_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_crm_charger_ready_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_crm_charger_ready_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_crm_charger_ready_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_crm_charger_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_crm_charger_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_crm_charger_status_is_in_range(uint8_t value);

/**
 * Pack message CTS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_cts_pack(
    uint8_t *dst_p,
    const struct gbt27930_cts_t *src_p,
    size_t size);

/**
 * Unpack message CTS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_cts_unpack(
    struct gbt27930_cts_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CTS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_cts_init(struct gbt27930_cts_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_cts_estimated_charge_time_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_cts_estimated_charge_time_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_cts_estimated_charge_time_is_in_range(uint16_t value);

/**
 * Pack message CML.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_cml_pack(
    uint8_t *dst_p,
    const struct gbt27930_cml_t *src_p,
    size_t size);

/**
 * Unpack message CML.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_cml_unpack(
    struct gbt27930_cml_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CML.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_cml_init(struct gbt27930_cml_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_cml_charger_mode_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_cml_charger_mode_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_cml_charger_mode_is_in_range(uint8_t value);

/**
 * Pack message CRO.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_cro_pack(
    uint8_t *dst_p,
    const struct gbt27930_cro_t *src_p,
    size_t size);

/**
 * Unpack message CRO.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_cro_unpack(
    struct gbt27930_cro_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CRO.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_cro_init(struct gbt27930_cro_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_cro_charger_ready_to_charge_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_cro_charger_ready_to_charge_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_cro_charger_ready_to_charge_is_in_range(uint8_t value);

/**
 * Pack message CCS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_ccs_pack(
    uint8_t *dst_p,
    const struct gbt27930_ccs_t *src_p,
    size_t size);

/**
 * Unpack message CCS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_ccs_unpack(
    struct gbt27930_ccs_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CCS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_ccs_init(struct gbt27930_ccs_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_ccs_output_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_ccs_output_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_ccs_output_voltage_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_ccs_output_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_ccs_output_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_ccs_output_current_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_ccs_charger_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_ccs_charger_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_ccs_charger_temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_ccs_charger_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_ccs_charger_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_ccs_charger_status_is_in_range(uint8_t value);

/**
 * Pack message CST.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_cst_pack(
    uint8_t *dst_p,
    const struct gbt27930_cst_t *src_p,
    size_t size);

/**
 * Unpack message CST.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_cst_unpack(
    struct gbt27930_cst_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CST.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_cst_init(struct gbt27930_cst_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t gbt27930_cst_stop_reason_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_cst_stop_reason_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_cst_stop_reason_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_cst_fault_code_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_cst_fault_code_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_cst_fault_code_is_in_range(uint16_t value);

/**
 * Pack message CSD.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_csd_pack(
    uint8_t *dst_p,
    const struct gbt27930_csd_t *src_p,
    size_t size);

/**
 * Unpack message CSD.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_csd_unpack(
    struct gbt27930_csd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CSD.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_csd_init(struct gbt27930_csd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_csd_discharge_time_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_csd_discharge_time_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_csd_discharge_time_is_in_range(uint16_t value);

/**
 * Pack message CEM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int gbt27930_cem_pack(
    uint8_t *dst_p,
    const struct gbt27930_cem_t *src_p,
    size_t size);

/**
 * Unpack message CEM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int gbt27930_cem_unpack(
    struct gbt27930_cem_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from CEM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int gbt27930_cem_init(struct gbt27930_cem_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t gbt27930_cem_error_code_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double gbt27930_cem_error_code_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool gbt27930_cem_error_code_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
