/**
 * @file gbt27930.c
 *
 * @brief This source file was generated by cantools version 41.2.1 Fri Mar 13 18:52:59 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "gbt27930.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int gbt27930_bhm_pack(
    uint8_t *dst_p,
    const struct gbt27930_bhm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_version, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->battery_capacity, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->battery_capacity, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->nominal_voltage, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->nominal_voltage, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->battery_type, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->manufacturer_id, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->manufacturer_id, 8u, 0xffu);

    return (8);
}

int gbt27930_bhm_unpack(
    struct gbt27930_bhm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_version = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->battery_capacity = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->battery_capacity |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->nominal_voltage = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->nominal_voltage |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->battery_type = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->manufacturer_id = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->manufacturer_id |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int gbt27930_bhm_init(struct gbt27930_bhm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bhm_t));

    return 0;
}

uint8_t gbt27930_bhm_bms_version_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_bhm_bms_version_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_bhm_bms_version_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t gbt27930_bhm_battery_capacity_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bhm_battery_capacity_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bhm_battery_capacity_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t gbt27930_bhm_nominal_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bhm_nominal_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bhm_nominal_voltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint8_t gbt27930_bhm_battery_type_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_bhm_battery_type_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_bhm_battery_type_is_in_range(uint8_t value)
{
    return (value <= 10u);
}

uint16_t gbt27930_bhm_manufacturer_id_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_bhm_manufacturer_id_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_bhm_manufacturer_id_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int gbt27930_brm_pack(
    uint8_t *dst_p,
    const struct gbt27930_brm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->series_cells, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->series_cells, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->parallel_cells, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->parallel_cells, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->pack_capacity, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->pack_capacity, 8u, 0xffu);

    return (8);
}

int gbt27930_brm_unpack(
    struct gbt27930_brm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->series_cells = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->series_cells |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->parallel_cells = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->parallel_cells |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->pack_capacity = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->pack_capacity |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int gbt27930_brm_init(struct gbt27930_brm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_brm_t));

    return 0;
}

uint16_t gbt27930_brm_series_cells_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_brm_series_cells_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_brm_series_cells_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint16_t gbt27930_brm_parallel_cells_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_brm_parallel_cells_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_brm_parallel_cells_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint16_t gbt27930_brm_pack_capacity_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_brm_pack_capacity_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_brm_pack_capacity_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

int gbt27930_bcp_pack(
    uint8_t *dst_p,
    const struct gbt27930_bcp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->max_charge_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->max_charge_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->max_charge_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->max_charge_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->energy_capacity, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->energy_capacity, 8u, 0xffu);

    return (8);
}

int gbt27930_bcp_unpack(
    struct gbt27930_bcp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_charge_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->max_charge_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->max_charge_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->max_charge_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->energy_capacity = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->energy_capacity |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int gbt27930_bcp_init(struct gbt27930_bcp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bcp_t));

    return 0;
}

uint16_t gbt27930_bcp_max_charge_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bcp_max_charge_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bcp_max_charge_voltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t gbt27930_bcp_max_charge_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bcp_max_charge_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bcp_max_charge_current_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t gbt27930_bcp_energy_capacity_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bcp_energy_capacity_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bcp_energy_capacity_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

int gbt27930_bro_pack(
    uint8_t *dst_p,
    const struct gbt27930_bro_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_ready, 0u, 0xffu);

    return (8);
}

int gbt27930_bro_unpack(
    struct gbt27930_bro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_ready = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int gbt27930_bro_init(struct gbt27930_bro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bro_t));

    return 0;
}

uint8_t gbt27930_bro_bms_ready_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_bro_bms_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_bro_bms_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int gbt27930_bcl_pack(
    uint8_t *dst_p,
    const struct gbt27930_bcl_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->requested_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->requested_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->requested_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->requested_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->charge_mode, 0u, 0xffu);

    return (8);
}

int gbt27930_bcl_unpack(
    struct gbt27930_bcl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->requested_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->requested_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->requested_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->requested_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->charge_mode = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int gbt27930_bcl_init(struct gbt27930_bcl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bcl_t));

    return 0;
}

uint16_t gbt27930_bcl_requested_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bcl_requested_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bcl_requested_voltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t gbt27930_bcl_requested_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bcl_requested_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bcl_requested_current_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint8_t gbt27930_bcl_charge_mode_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_bcl_charge_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_bcl_charge_mode_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

int gbt27930_bcs_pack(
    uint8_t *dst_p,
    const struct gbt27930_bcs_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->battery_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->battery_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->battery_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->battery_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->soc, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->battery_temp, 0u, 0xffu);

    return (8);
}

int gbt27930_bcs_unpack(
    struct gbt27930_bcs_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->battery_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->battery_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->battery_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->battery_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->soc = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->battery_temp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int gbt27930_bcs_init(struct gbt27930_bcs_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bcs_t));

    return 0;
}

uint16_t gbt27930_bcs_battery_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bcs_battery_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bcs_battery_voltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t gbt27930_bcs_battery_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_bcs_battery_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_bcs_battery_current_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint8_t gbt27930_bcs_soc_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_bcs_soc_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_bcs_soc_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t gbt27930_bcs_battery_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double gbt27930_bcs_battery_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool gbt27930_bcs_battery_temp_is_in_range(uint8_t value)
{
    return (value <= 160u);
}

int gbt27930_bsm_pack(
    uint8_t *dst_p,
    const struct gbt27930_bsm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->max_temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->min_temp, 0u, 0xffu);

    return (8);
}

int gbt27930_bsm_unpack(
    struct gbt27930_bsm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_temp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->min_temp = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int gbt27930_bsm_init(struct gbt27930_bsm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bsm_t));

    return 0;
}

uint8_t gbt27930_bsm_max_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double gbt27930_bsm_max_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool gbt27930_bsm_max_temp_is_in_range(uint8_t value)
{
    return (value <= 160u);
}

uint8_t gbt27930_bsm_min_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double gbt27930_bsm_min_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool gbt27930_bsm_min_temp_is_in_range(uint8_t value)
{
    return (value <= 160u);
}

int gbt27930_bmv_pack(
    uint8_t *dst_p,
    const struct gbt27930_bmv_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->max_cell_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->max_cell_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->min_cell_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->min_cell_voltage, 8u, 0xffu);

    return (8);
}

int gbt27930_bmv_unpack(
    struct gbt27930_bmv_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_cell_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->max_cell_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->min_cell_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->min_cell_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int gbt27930_bmv_init(struct gbt27930_bmv_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bmv_t));

    return 0;
}

uint16_t gbt27930_bmv_max_cell_voltage_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double gbt27930_bmv_max_cell_voltage_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool gbt27930_bmv_max_cell_voltage_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t gbt27930_bmv_min_cell_voltage_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double gbt27930_bmv_min_cell_voltage_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool gbt27930_bmv_min_cell_voltage_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int gbt27930_bmt_pack(
    uint8_t *dst_p,
    const struct gbt27930_bmt_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->max_temp_cell, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->min_temp_cell, 0u, 0xffu);

    return (8);
}

int gbt27930_bmt_unpack(
    struct gbt27930_bmt_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_temp_cell = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->min_temp_cell = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int gbt27930_bmt_init(struct gbt27930_bmt_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bmt_t));

    return 0;
}

uint8_t gbt27930_bmt_max_temp_cell_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double gbt27930_bmt_max_temp_cell_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool gbt27930_bmt_max_temp_cell_is_in_range(uint8_t value)
{
    return (value <= 160u);
}

uint8_t gbt27930_bmt_min_temp_cell_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double gbt27930_bmt_min_temp_cell_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool gbt27930_bmt_min_temp_cell_is_in_range(uint8_t value)
{
    return (value <= 160u);
}

int gbt27930_bsp_pack(
    uint8_t *dst_p,
    const struct gbt27930_bsp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->stop_reason, 0u, 0xffu);

    return (8);
}

int gbt27930_bsp_unpack(
    struct gbt27930_bsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->stop_reason = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int gbt27930_bsp_init(struct gbt27930_bsp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bsp_t));

    return 0;
}

uint8_t gbt27930_bsp_stop_reason_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_bsp_stop_reason_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_bsp_stop_reason_is_in_range(uint8_t value)
{
    return (value <= 20u);
}

int gbt27930_bst_pack(
    uint8_t *dst_p,
    const struct gbt27930_bst_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->stop_flag, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->fault_code, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->fault_code, 8u, 0xffu);

    return (8);
}

int gbt27930_bst_unpack(
    struct gbt27930_bst_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->stop_flag = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fault_code = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->fault_code |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);

    return (0);
}

int gbt27930_bst_init(struct gbt27930_bst_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bst_t));

    return 0;
}

uint8_t gbt27930_bst_stop_flag_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_bst_stop_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_bst_stop_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t gbt27930_bst_fault_code_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_bst_fault_code_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_bst_fault_code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int gbt27930_bsd_pack(
    uint8_t *dst_p,
    const struct gbt27930_bsd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->discharge_time, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->discharge_time, 8u, 0xffu);

    return (8);
}

int gbt27930_bsd_unpack(
    struct gbt27930_bsd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->discharge_time = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->discharge_time |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int gbt27930_bsd_init(struct gbt27930_bsd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bsd_t));

    return 0;
}

uint16_t gbt27930_bsd_discharge_time_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_bsd_discharge_time_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_bsd_discharge_time_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int gbt27930_bem_pack(
    uint8_t *dst_p,
    const struct gbt27930_bem_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->error_code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->error_code, 8u, 0xffu);

    return (8);
}

int gbt27930_bem_unpack(
    struct gbt27930_bem_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->error_code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->error_code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int gbt27930_bem_init(struct gbt27930_bem_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_bem_t));

    return 0;
}

uint16_t gbt27930_bem_error_code_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_bem_error_code_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_bem_error_code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int gbt27930_chm_pack(
    uint8_t *dst_p,
    const struct gbt27930_chm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->charger_max_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->charger_max_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->charger_max_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->charger_max_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->charger_type, 0u, 0xffu);

    return (8);
}

int gbt27930_chm_unpack(
    struct gbt27930_chm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->charger_max_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->charger_max_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->charger_max_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->charger_max_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->charger_type = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int gbt27930_chm_init(struct gbt27930_chm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_chm_t));

    return 0;
}

uint16_t gbt27930_chm_charger_max_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_chm_charger_max_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_chm_charger_max_voltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t gbt27930_chm_charger_max_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_chm_charger_max_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_chm_charger_max_current_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint8_t gbt27930_chm_charger_type_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_chm_charger_type_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_chm_charger_type_is_in_range(uint8_t value)
{
    return (value <= 10u);
}

int gbt27930_crm_pack(
    uint8_t *dst_p,
    const struct gbt27930_crm_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->charger_ready, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->charger_status, 0u, 0xffu);

    return (8);
}

int gbt27930_crm_unpack(
    struct gbt27930_crm_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->charger_ready = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->charger_status = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int gbt27930_crm_init(struct gbt27930_crm_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_crm_t));

    return 0;
}

uint8_t gbt27930_crm_charger_ready_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_crm_charger_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_crm_charger_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t gbt27930_crm_charger_status_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_crm_charger_status_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_crm_charger_status_is_in_range(uint8_t value)
{
    return (value <= 10u);
}

int gbt27930_cts_pack(
    uint8_t *dst_p,
    const struct gbt27930_cts_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->estimated_charge_time, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->estimated_charge_time, 8u, 0xffu);

    return (8);
}

int gbt27930_cts_unpack(
    struct gbt27930_cts_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->estimated_charge_time = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->estimated_charge_time |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int gbt27930_cts_init(struct gbt27930_cts_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_cts_t));

    return 0;
}

uint16_t gbt27930_cts_estimated_charge_time_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_cts_estimated_charge_time_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_cts_estimated_charge_time_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int gbt27930_cml_pack(
    uint8_t *dst_p,
    const struct gbt27930_cml_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->charger_mode, 0u, 0xffu);

    return (8);
}

int gbt27930_cml_unpack(
    struct gbt27930_cml_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->charger_mode = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int gbt27930_cml_init(struct gbt27930_cml_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_cml_t));

    return 0;
}

uint8_t gbt27930_cml_charger_mode_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_cml_charger_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_cml_charger_mode_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

int gbt27930_cro_pack(
    uint8_t *dst_p,
    const struct gbt27930_cro_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->charger_ready_to_charge, 0u, 0xffu);

    return (8);
}

int gbt27930_cro_unpack(
    struct gbt27930_cro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->charger_ready_to_charge = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int gbt27930_cro_init(struct gbt27930_cro_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_cro_t));

    return 0;
}

uint8_t gbt27930_cro_charger_ready_to_charge_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_cro_charger_ready_to_charge_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_cro_charger_ready_to_charge_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int gbt27930_ccs_pack(
    uint8_t *dst_p,
    const struct gbt27930_ccs_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->output_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->output_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->output_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->output_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->charger_temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->charger_status, 0u, 0xffu);

    return (8);
}

int gbt27930_ccs_unpack(
    struct gbt27930_ccs_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->output_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->output_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->output_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->output_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->charger_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->charger_status = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int gbt27930_ccs_init(struct gbt27930_ccs_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_ccs_t));

    return 0;
}

uint16_t gbt27930_ccs_output_voltage_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_ccs_output_voltage_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_ccs_output_voltage_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t gbt27930_ccs_output_current_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double gbt27930_ccs_output_current_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool gbt27930_ccs_output_current_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint8_t gbt27930_ccs_charger_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double gbt27930_ccs_charger_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool gbt27930_ccs_charger_temp_is_in_range(uint8_t value)
{
    return (value <= 160u);
}

uint8_t gbt27930_ccs_charger_status_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_ccs_charger_status_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_ccs_charger_status_is_in_range(uint8_t value)
{
    return (value <= 10u);
}

int gbt27930_cst_pack(
    uint8_t *dst_p,
    const struct gbt27930_cst_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->stop_reason, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->fault_code, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->fault_code, 8u, 0xffu);

    return (8);
}

int gbt27930_cst_unpack(
    struct gbt27930_cst_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->stop_reason = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fault_code = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->fault_code |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);

    return (0);
}

int gbt27930_cst_init(struct gbt27930_cst_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_cst_t));

    return 0;
}

uint8_t gbt27930_cst_stop_reason_encode(double value)
{
    return (uint8_t)(value);
}

double gbt27930_cst_stop_reason_decode(uint8_t value)
{
    return ((double)value);
}

bool gbt27930_cst_stop_reason_is_in_range(uint8_t value)
{
    return (value <= 20u);
}

uint16_t gbt27930_cst_fault_code_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_cst_fault_code_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_cst_fault_code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int gbt27930_csd_pack(
    uint8_t *dst_p,
    const struct gbt27930_csd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->discharge_time, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->discharge_time, 8u, 0xffu);

    return (8);
}

int gbt27930_csd_unpack(
    struct gbt27930_csd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->discharge_time = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->discharge_time |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int gbt27930_csd_init(struct gbt27930_csd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_csd_t));

    return 0;
}

uint16_t gbt27930_csd_discharge_time_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_csd_discharge_time_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_csd_discharge_time_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int gbt27930_cem_pack(
    uint8_t *dst_p,
    const struct gbt27930_cem_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->error_code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->error_code, 8u, 0xffu);

    return (8);
}

int gbt27930_cem_unpack(
    struct gbt27930_cem_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->error_code = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->error_code |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int gbt27930_cem_init(struct gbt27930_cem_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct gbt27930_cem_t));

    return 0;
}

uint16_t gbt27930_cem_error_code_encode(double value)
{
    return (uint16_t)(value);
}

double gbt27930_cem_error_code_decode(uint16_t value)
{
    return ((double)value);
}

bool gbt27930_cem_error_code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
